# Generated by Django 6.0 on 2025-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(default='ZZ', max_length=2),
            preserve_default=False,
        ),
    ]
