# Generated by Django 6.0 on 2025-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0003_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='elevation',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
    ]
