# Generated by Django 6.0 on 2025-12-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0004_station_elevation_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='stationId',
            new_name='station_id',
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_avg', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_logs.station')),
            ],
        ),
    ]
