# Generated by Django 6.0 on 2025-12-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0005_rename_stationid_station_station_id_daily'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily',
            new_name='DailyTemp',
        ),
    ]
