# Generated by Django 6.0 on 2025-12-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0006_rename_daily_dailytemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytemp',
            old_name='station',
            new_name='station_id',
        ),
    ]
