# Generated by Django 6.0 on 2025-12-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_logs', '0007_rename_station_dailytemp_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytemp',
            name='temp_avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailytemp',
            name='temp_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailytemp',
            name='temp_min',
            field=models.IntegerField(null=True),
        ),
    ]
